class Tonal::Scale::Genus < Tonal::Scale
  def init_sequence
    Tonal::Sequence::Genus.new(factors: @args[:factors])
  end

  def name
    "Euler-Fokker genus, #{genus_notation}"
  end

  def description
    "Euler-Fokker genus: harmonic-space lattice generated by #{genus_notation}"
  end

  private
  def genus_notation
    @args[:factors].map{|prime, exponent| "#{prime}^#{exponent}"}.join(".")
  end
end
